const config = {
    "latitude": 1.298759,
    "longitude": 103.778329,
    "g_solar_min": 0,
    "g_solar_max": 50,
    "g_sky_min": 50,
    "g_sky_max": 100,
    "g_uhi_min": 0,
    "g_uhi_max": 4,
    "g_wind_min": 60,
    "g_wind_max": 100,
    "g_irr_min": 0,
    "g_irr_max": 800,
    "g_irr_rad_min": 0,
    "g_irr_rad_max": 800,
    "f_solar_min": 0,
    "f_solar_max": 50,
    "f_sky_min": 50,
    "f_sky_max": 100,
    "f_irr_min": 0,
    "f_irr_max": 500,
    "f_irr_rad_min": 0,
    "f_irr_rad_max": 500,
    "f_noise_min": 0,
    "f_noise_max": 60,
    "f_unob_min": 80,
    "f_unob_max": 100,
    "f_visib_min": 0,
    "f_visib_max": 60,
}
module.exports = {
    config: config,
}